version: '3.8'

services:
  postgres:
    container_name: PizzeriaDB
    image: postgres:14.0
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "exit 0"
  
  pizzeria:
    container_name: PizzeriaAPP
    build: .
    image: pizzeriaapp
    ports: 
      - ${PIZZERIA_EXTERNAL_PORT}:8000
    depends_on:
      postgres:
        condition: service_healthy
