version: '3.8'

services:
  postgres:
    container_name: PizzeriaDB
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"
  
  pizzeria:
    container_name: PizzeriaAPP
    build: .
    ports: 
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
