INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Margheritta', 'Pizza', 20);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Vegetariana', 'Pizza', 22);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Tosca', 'Pizza', 25);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Venecia', 'Pizza', 25);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Double Cheese', 'Pizza Addons', 2);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Salami', 'Pizza Addons', 2);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Ham', 'Pizza Addons', 2);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Mushrooms', 'Pizza Addons', 2);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Schnitzel', 'Main Dish', 30);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Fish and Chips', 'Main Dish', 28);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Hungarian Cake', 'Main Dish', 27);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Salads', 'Side Dish', 5);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Sauces', 'Side Dish', 6);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Tomato Soup', 'Soup', 12);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Chicken Soup', 'Soup', 10);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Coffee', 'Drinks', 5);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Tea', 'Drinks', 5);
INSERT INTO public."menu" ("Name", "Category", "Price") VALUES ('Coke', 'Drinks', 5);